FROM node:22.17.1-alpine

RUN apk add --no-cache \
    chromium \
    nss \
    ca-certificates \
    && rm -rf /var/cache/apk/*  # Limpiar caché de APK



# Configurar Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./


RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/index.js"]